server:
  port: 8081

spring:
  application:
    name: Thresh-Application S3 storage
  datasource:
    url: jdbc:postgresql://localhost:5443/thresh
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

